import NavigationBar from "@/components/ui/NavigationBar";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "@/components/ui/Footer";
import { Layout } from "antd";

const { Content, Header } = Layout;
const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"]
});

export const metadata = {
  title: "WTA - Web Transport Adviser",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="flex flex-col h-screen">
          <Layout>
            <Header>
              <NavigationBar />
            </Header>
          </Layout>
          <NavigationBar />
          <div className="flex grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
